### ISSUE TITLE
ホーム画面と集荷状況の結果表示画面を連携させたい。

### ISSUE THREAD

**Issue by OyamaMiho** [OyamaMiho/collecting-status#5]
## Description
ホーム画面と集荷状況の結果表示画面を連携させたい。

## イメージ図
<img width="275" alt="2018-10-16 13 17 23" src="https://user-images.githubusercontent.com/40228120/46992610-dd447580-d145-11e8-944f-7a120d5a7251.png">
矢印の`search`ボタンを押すと、集荷状況の結果画面（show.html.haml）に飛ぶようにしたい。

## 実施したこと
``index.html.haml``（ホーム画面のview）に``= link_to '検索’, ‘/search_results/:id’``でリンク先を指定する。
1. エラーが出たため、実装が間違っていると考えた。
1. 解決方法が分からずissueを立てるに至った。

### 該当コード
- collecting_status_controller.rb
```
class CollectingStatusController < ApplicationController
  def index
    @slip_number = params[:slip_number]
    @specified_date_time = params[:specified_date_time]
    @search = params[:search]
  end
end
```

- index.html.haml
```
%form.index{action: "\#{url_for :controller => 'collecting_status', :action => 'create'}", method: "post"}
- provide(:title, "collecting_status")
%h1 集荷状況の確認
.row
.col-md-6.col-md-offset-3
.slip_number
%p
= label :slip_number, '伝票番号:'
= text_field_tag :slip_number, @slip_number
.specified_date_time
-# = date_select :page, :updated_at
= date_select(                      |
:use_two_digit_numbers,           |
start_year: 2018,                 |
end_year:   Time.current.year,  |
default:    Date.new(2018, 1, 1)) |
.search
= submit_tag "search", class: "btn btn-primary"
= link_to '検索’, ‘/search_results/:id’
```
### 参考サイト
- [submit_tag](http://railsdoc.com/references/submit_tag)
- [https://stackoverflow.com/questions/6956677/link-submit-to-another-page](https://stackoverflow.com/questions/6956677/link-submit-to-another-page)

**Comment by yusakuniwa** [comment]
@OyamaMiho どんなエラーが出たんでしょうか。

**Comment by OyamaMiho** [comment]
@yusakuniwa 
下記エラー内容です。
<img width="923" alt="2018-10-16 14 53 15" src="https://user-images.githubusercontent.com/40228120/46995347-45e61f00-d153-11e8-93d9-8cea504e1878.png">

**Comment by ichimaru-daiki** [comment]
search_result_path(@search)ではないですか？

**Comment by j-hanyu** [comment]
> `@search`としたところ、指定するkey（id）が無いとのエラーが出たため、
> `id`としたことで解決出来ました。

これは内容を理解した上で変更しているのでしょうか？
文面を見るととりあえずエラーがなくなったのでそうしたように取れます。
内容を理解して変更しないと正しく動かないと思います

**Comment by ichimaru-daiki** [comment]
@OyamaMiho 
rails consoleで `show-routes -G search_result`をした結果を
貼り付けてもらっていいですか？

**Comment by OyamaMiho** [comment]
@j-hanyu 
丹羽さんに教えていただき、理解出来ました。
私は集荷状況の結果表示画面のアクションを`show`にしています。
showは、一意のデータをidとして設定し、そのidに基づき、詳細画面が表示されることが分かりました。
ですので、実装時は`id`ではなく、`/show/ヤマト（運輸業者）/○○○○（伝票番号）`とルーティングを設定しようと思います。
根本的な理解が出来ていない、または浅いことに改めて気付いたので、分からない箇所1つにしても自分で仕組みを理解してから進めるようにします。

**Comment by OyamaMiho** [comment]
@ichimaru-daiki 
show-routes -G search_resultをした結果が下記です。
```
[1] pry(main)> show-routes -G search_result
            search_result GET  /search_results/:id(.:format)                                                            search_results#show
```
